[build]
  command = "npm run build"
  publish = "build"
  base = "client"

[functions]
  directory = "../server/functions"
  node_bundler = "esbuild"
  included_files = ["../server/functions/package.json"]

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 