[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[functions]
  directory = "server"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 