[build]
  base = "client"
  command = "npm install && npm run build && cd ../server/functions && npm install"
  publish = "build"

[functions]
  directory = "../server/functions"
  node_bundler = "esbuild"
  external_node_modules = ["yt-dlp-wrap"]

[functions.info]
  included_files = ["../server/functions/node_modules/yt-dlp-wrap/bin/*"]

[functions.download]
  included_files = ["../server/functions/node_modules/yt-dlp-wrap/bin/*"]

[build.environment]
  NODE_VERSION = "18"
  YT_DLP_NO_UPDATE = "1"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 