[build]
  base = "client"
  publish = "build"
  command = "npm run build"

[functions]
  directory = "server/functions"

# Handle API requests first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Handle static assets
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true

# Handle all other routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 